INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, '7_colour_pots', '10000', 'Best for decor', 'pots', '7_colour_pots.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Flo_art_Multicolor', '1500', 'Best for rich decor', 'pots', 'pot1.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'garden_decor_pots', '6000', 'Best for gardendecor', 'pots', 'garden_decor_pots.jpg', 45);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'indoor_flower_pots', '2000', 'Best for indoor', 'pots', 'indoor_flower_pots.jpg', 40);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'floral_print_semi_sheer', '13000', 'Best for door', 'curtains', 'curtain1.jpg', 35);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'gold_polyester_tradational', '4000', 'Best cloth', 'curtains', 'gold_polyester_tradational.jpg', 30);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'printed_curtains', '2000', 'Best for rich decor', 'curtains', 'printed_curtains.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'crystal_lamp', '3000', 'Best for living room', 'lamps', 'crystal_lamp.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'floor_lamps', '2000', 'Best for floor lamp', 'lamps', 'floor_lamps.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'hanging_led_outdoor_lamps', '6000', 'Best for hanging', 'lamps', 'hanging_led_outdoor_lamps.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'lyse_decor_handcrafted_glass_downside_wall_hanging', '8000', 'Best for downside decor', 'lamps', 'lyse_decor_handcrafted_glass_downside_wall_hanging.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Feather_wall_mirror', '10000', 'Best for wall decor', 'mirror', 'mirror2.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Glass_reactangle_wall_mirror', '2000', 'Best for living room', 'mirror', 'mirror3.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'Living_room_decor', '5999', 'Best for kitchen', 'mirror', 'Living_room_decor.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'designer_sofa', '5300', 'Best for design', 'Sofa', 'designer_sofa.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'fully_carved_wooden_royal', '5800', 'Best wooden sofa', 'Sofa', 'fully_carved_wooden_royal.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'furny_doriana_fabric_4_seater', '32459', 'Best fabric sofa', 'Sofa', 'furny_doriana_fabric_4_seater.jpg', 50);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'lexas_fabric_5_seater', '80000', 'Best for 5 seater', 'Sofa', 'lexas_fabric_5_seater.jpg', 45);
